version: '3.3'
services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: 'finanservs'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'rsanchez'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'cafekotowa'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'fncafekotowa'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - finanservs:/var/lib/mysql
# Names our volume
volumes:
  finanservs: